### ISSUE TITLE
Problem with compilling "libbthread"

### ISSUE THREAD

**Issue by hfjdkedf** [Saikatsaha1996/cgminer-android#1]
After "make install" i get an error that path not found even though the libbthread folder is in /data/data/com.termux/files/home/
![Без названия](https://user-images.githubusercontent.com/14019785/170773168-277e639e-8301-406e-964e-4289224ed407.png)
Please, help me.

**Comment by Saikatsaha1996** [comment]
This is not error your libbthread already installed

**Comment by hfjdkedf** [comment]
oh, thank you;)
